apiVersion: v1
kind: Service
metadata:
  name: rabbitmq-cluster-ip-service
spec:
  selector:
    component: rabbitmq
  ports:
    - name: rabbitmq
      protocol: TCP
      port: 5672
      targetPort: 5672
  